version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    reviewers:
      - 'cassinodev'
    assignees:
      - 'cassinodev'
    commit-message:
      prefix: 'chore'
      include: 'scope'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    reviewers:
      - 'cassinodev'
    assignees:
      - 'cassinodev'
    commit-message:
      prefix: 'ci'
      include: 'scope'
