import fs from 'fs';
import path from 'path';
import YAML from 'yaml';

const template = `
// ⚠️ AUTOGENERATED FILE: file generated by scripts/generateFonts.js in home path'
// Please, don't edit this file manually, it will be overwritten on the next run of the script.
export const fontIcons = {
{{content}}
}

export type IconKey = keyof typeof fontIcons;
`;

const acceptedStyles = ['solid', 'regular', 'brands'];

const getAllFonts = async () => {
  const url =
    'https://raw.githubusercontent.com/FortAwesome/Font-Awesome/refs/heads/6.x/metadata/icons.yml';
  const req = await fetch(url);
  const data = await req.text();
  return YAML.parse(data);
};

(async () => {
  const yamlFile = await getAllFonts();
  const content = [];
  Object.keys(yamlFile).forEach(key => {
    const name = key;
    const item = yamlFile[key];

    if (
      item.unicode &&
      item.styles.length > 0 &&
      item.styles.some(style => acceptedStyles.includes(style))
    ) {
      if (item.styles.length == 1) {
        content.push(`  '${name}': { hexCode: '${item.unicode}' },`);
        return;
      }
    }
  });

  const finalContent = template.replace('{{content}}', content.join('\n'));

  fs.writeFileSync(path.join('./src/constants/icons.ts'), finalContent);
})();
