import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const packageJsonPath = resolve(__dirname, '../package.json');
const versionTsPath = resolve(__dirname, '../src/version.ts');

const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
const version = packageJson.version;

const versionTsContent = `// This file is auto-generated by scripts/generate-version.js
// Do not edit manually

export const PHASER_HOOKS_VERSION = '${version}' as const;
`;

writeFileSync(versionTsPath, versionTsContent, 'utf-8');
console.log(`✅ Generated version.ts with version: ${version}`);

