name: Deploy Storybook (phaser-toolkit-demo)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to GitHub Pages'
        required: true
        default: true
        type: boolean

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build libs
        run: pnpm build

      - name: Build Storybook (packages/phaser-toolkit-demo)
        run: pnpm --filter "./packages/phaser-toolkit-demo" build-storybook

      - name: Deploy to GitHub Pages (gh-pages)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: packages/phaser-toolkit-demo/storybook-static
